# Generated by Django 4.2.21 on 2025-06-04 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('user_pw', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_no', models.AutoField(primary_key=True, serialize=False)),
                ('sido', models.CharField(blank=True, max_length=100, null=True)),
                ('sigungu', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelfareProgram',
            fields=[
                ('w_no', models.AutoField(primary_key=True, serialize=False)),
                ('w_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserJobInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_job', models.CharField(blank=True, max_length=100, null=True)),
                ('user_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('user_income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WelfareCriteria',
            fields=[
                ('welfare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.welfareprogram')),
                ('income_eligibility', models.FloatField()),
                ('age_eligibility', models.IntegerField(blank=True, null=True)),
                ('classification_eligibility', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelfarePeriod',
            fields=[
                ('welfare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.welfareprogram')),
                ('p_issuance', models.DateField()),
                ('p_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_birthdate', models.DateField(blank=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_point', models.IntegerField()),
                ('is_eligible', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('welfare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.welfareprogram')),
            ],
            options={
                'unique_together': {('user', 'welfare')},
            },
        ),
    ]
