# Generated by Django 5.2.1 on 2025-05-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_no", models.AutoField(primary_key=True, serialize=False)),
                ("sido", models.CharField(blank=True, max_length=100, null=True)),
                ("sigungu", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_no", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=100)),
                ("user_pw", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WelfareProgram",
            fields=[
                ("w_no", models.AutoField(primary_key=True, serialize=False)),
                ("w_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserJobInfo",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.user",
                    ),
                ),
                ("user_job", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user_classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_income", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="WelfareCriteria",
            fields=[
                (
                    "welfare",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.welfareprogram",
                    ),
                ),
                ("income_eligibility", models.FloatField()),
                ("age_eligibility", models.IntegerField(blank=True, null=True)),
                (
                    "classification_eligibility",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WelfarePeriod",
            fields=[
                (
                    "welfare",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.welfareprogram",
                    ),
                ),
                ("p_issuance", models.DateField()),
                ("p_end", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.user",
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=100, null=True)),
                ("user_birthdate", models.DateField(blank=True, null=True)),
                ("user_email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user_phone_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_point", models.IntegerField()),
                ("is_eligible", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
                (
                    "welfare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.welfareprogram",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "welfare")},
            },
        ),
    ]
